# Generated by Django 5.2.1 on 2025-05-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance en km', max_digits=10)),
                ('duration', models.IntegerField(help_text='Durée en minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_arrivals', to='api.location')),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_departures', to='api.location')),
            ],
        ),
    ]
